### Pandas Basic
Pandas is a wrapper of 2 languages:
- Numpy - numerical data and mathemetical operations
- Matplotlib - data visualization

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

Pandas Datastructures
# Series- single dimensional datastructure
  - Similare to a list or a single column,  
  - homogeneous (of the same data type)
#    DataFrame-multidimensional table
-   heterogeneous (of many datatypes)

In [3]:
ser1 = pd.Series([10,20,30,40], index=["A","B","C","D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [4]:
ser1.loc["A"]

np.int64(10)

In [5]:
ser1.iloc[0]

np.int64(10)

In [6]:
#creating a series from a pre-exiting dictionary
d = {
    "a": 1,
    "b": 0,
    "c": 2,
    "d": 100    
}
print(d)

{'a': 1, 'b': 0, 'c': 2, 'd': 100}

In [7]:
pd.Series(d)

a      1
b      0
c      2
d    100
dtype: int64

In [8]:
ser2 = pd.Series(d)
print(ser2)

a      1
b      0
c      2
d    100
dtype: int64

In [9]:
d1 = {
    "a": 1.3,
    "b": 0.5,
    "c": 2.4    
}

ser3 = pd.Series(d1)
print(ser3)

a    1.3
b    0.5
c    2.4
dtype: float64

In [10]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}
ser4 = pd.Series(calories, index=['day1', 'day3'])
print(ser4)

day1     700
day3    1200
dtype: int64

In [11]:
ser5 = pd.Series(5.0, index=["a","b","c"])
print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frame - Index and column

In [12]:
fruit_data = {
    'apple_sales': [3,2,3,5,7,0,2,2],
    'orange_sales': [3,2,5,5,8,0,2,2]
}
# idx = ['Day 1','Day 2','Day 3','Day 4','Day 5','Day 6','Day 7','Day 8']

idx = pd.RangeIndex(2000, 2008)
purchases = pd.DataFrame(fruit_data, index=[idx])
print(purchases)

      apple_sales  orange_sales
2000            3             3
2001            2             2
2002            3             5
2003            5             5
2004            7             8
2005            0             0
2006            2             2
2007            2             2

In [13]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Columns: {cols}')

Rows: 8
Columns: 2

In [14]:
purchases.head() #view first 5 elements

      apple_sales  orange_sales
2000            3             3
2001            2             2
2002            3             5
2003            5             5
2004            7             8

In [15]:
purchases.tail() # view bottom 5 elements

      apple_sales  orange_sales
2003            5             5
2004            7             8
2005            0             0
2006            2             2
2007            2             2

#### Importing Files with Pandas
.read_csv()
.read_excel()
.read_json()
.read_sql()

In [16]:
employee_df = pd.read_csv('data/employee.csv')
employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [17]:
rows, cols = employee_df.shape
print("Rows: ", rows)
print("Columns: ", cols)

Rows:  15
Columns:  4

In [18]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [19]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

In [20]:
student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [21]:
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [22]:
list_Index = student_df.columns
print('Columns Names', list_Index)

Columns Names Index(['Name', 'Age', 'Marks'], dtype='str')

In [23]:
cars_df = pd.read_json('data/cars.json')
cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [24]:
rows, cols = cars_df.shape
print("Rows: ", rows)
print("Columns: ", cols)

Rows:  161
Columns:  11

In [25]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

### EDA - Exploratory Data Analysis 
- Data profiling
    - Structure (shape)
    - Quality (missing value, duplicates, unique values)
    - Content (data types, dispersion, measure central tendency)
- Profiling Techniques
    - Data Type and format validation
    - Statistical summaries(descriptive stats, values counts, frequently checks)
    - Uniqueness and cardinality
    - Pattern recognition
    - Cross validation

In [26]:
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [27]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}
tech_df = pd.DataFrame(tech)

In [28]:
tech_df = tech_df.rename(columns ={'Courses': 'Course Name'})

In [29]:
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year

Sort Using Pandas --- 5/5/2026

In [30]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}
grades_df = pd.DataFrame(data)

grades_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [36]:
grades_df = ([grades_df.assign(address ='NYC', 'NJ', 'CA','PA')])

grades_df.head()

SyntaxError: positional argument follows keyword argument (1870320122.py, line 1)

In [35]:
#sort _values().sortby a ascending order
print(grades_df.sort_values(by='Score 1'))

     Name  Height Qualification  Score 1  Score 2
3    Fadi     5.2           Msc       45       30
0    Jane     5.1           Msc       56       50
2   James     5.1           Msc       77       60
1  Princi     6.2            MA       86       96

In [34]:
print(grades_df.sort_values(by='Score 1', ascending=False))

     Name  Height Qualification  Score 1  Score 2
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
0    Jane     5.1           Msc       56       50
3    Fadi     5.2           Msc       45       30

In [37]:
cars = pd.read_json('data/cars.json')

cars.head(15)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS
14,Datsun 1200,35.0,4,72.0,69,1613,18.0,71,Japan,99,TEXAS

In [40]:
print(cars.sort_values(by ='quantity', ascending = True))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
123                 Ford Torino  17.0          8         302.0         140
112         Ford Mustang II 2+2  25.5          4         140.0          89
6                    Chevy S-10  31.0          4         119.0          82
7              Chrysler Cordoba  15.5          8         400.0         190
121                 Ford Ranger  28.0          4         120.0          79
..                          ...   ...        ...           ...         ...
128                Honda Accord  36.0          4         107.0          75
134          Honda Civic (auto)  32.0          4          91.0          67
22                Datsun 310 GX  38.0          4          91.0          67
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
110             Ford Mustang GL  27.0          4         140.0          86

     Weight  Acceleration  Model Origin  quantity     city
123    3449          10.5     70     US         5       OH
112    2755          15.8     77     US         5       NJ
6      2720          19.4     82     US         7  NewYork
7      4325          12.2     77     US         7       NJ
121    2625          18.6     82     US         7   DALLAS
..      ...           ...    ...    ...       ...      ...
128    2205          14.5     82  Japan       427       OH
134    1965          15.7     82  Japan       430    TEXAS
22     1995          16.2     82  Japan       431       NJ
8      2585          14.5     82     US       434   DALLAS
110    2790          15.6     82     US       439       OH

[161 rows x 11 columns]

In [ ]:
# sort values by qty and by car
print(cars.sort_values ( by = ['quantity','car'] ascending = [False,True]))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3267184849.py, line 2)

Locate and ilocate
### Slicing a dataframe with .iloc[] & .loc[]
-  'df.loc[row:row , col:col]' - local based indexing
- `df.iloc[row:row, colNumber:colNumber] - indexbasedlocation

In [43]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]
e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [45]:
# first row
e_df.iloc[0]

Name        James
Age            36
Weight         75
Salary    5428000
Name: 0, dtype: object

In [46]:
# Grabs the first row
e_df.iloc[-1]

Name         John
Age            41
Weight         85
Salary    1528000
Name: 7, dtype: object

In [47]:
# grabs the first row
e_df.iloc[:1]

    Name  Age  Weight   Salary
0  James   36      75  5428000

In [48]:
e_df.iloc[0:4]

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000

In [51]:
# grabs all rows but only the first three columns
e_df.iloc[: , 0:3]

       Name  Age  Weight
0     James   36      75
1   Villers   38      74
2     VKole   31      70
3     Smith   34      80
4     Gayle   40     100
5    Rooter   33      72
6  Peterson   42      85
7      John   41      85

In [52]:
# grab first two rows and first two columns
e_df.iloc[0:2,0:2]

      Name  Age
0    James   36
1  Villers   38

In [56]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}

ball_up = pd.DataFrame(basketball)
ball_up.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [57]:
# locate all rows and columns team, rebounds
ball_up.loc[:, ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [60]:
# select values from row 3 -6 and show the team name
ball_up.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G

## Handling Missing values
- `df.isnull()` - to detect missing values (isNull = isna() is samething)
- `df.fillna()` - to fill the values ( imputation)
-  `df.dropna()` - to remove missing values
- `df.replace()` - to replace specific values(imputation)