## Handling Missing values
- `df.isnull()` - to detect missing values (isNull = isna() is samething)
- `df.fillna()` - to fill the values ( imputation)
-  `df.dropna()` - to remove missing values
- `df.replace()` - to replace specific values(imputation)

In [28]:
import numpy as np
import pandas as pd

In [29]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]

df =pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

In [30]:
# shape
rows,columns = df.shape
print(df.shape)
print(f'Total rows: {rows}, Total columns: {columns}')
print(f'Rows: {rows}')
print(f'Columns: {columns}')

(14, 4)
Total rows: 14, Total columns: 4
Rows: 14
Columns: 4

In [31]:
# View First 5 Entries
df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [32]:

#Provide a summarization of missing values per column
df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    2
dtype: int64

In [33]:
df.columns

Index(['Name', 'Age', 'Weight', 'Salary'], dtype='str')

In [34]:
# Be wary of missing values , if you have a small dataset, removing values can dramatically alter your analysis
# is missing data Rows is less than 5% of all data it is safe to remove and will have a little effect on analysis
dropped_df = df.dropna()
# when dropping na, you remove the entire row

print(dropped_df)

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [35]:
filled_df = df.fillna('None')

filled_df

        Name   Age Weight     Salary
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0   None  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0       None
9       None  42.0   85.0       None
10     Jenny  None  100.0    25632.0
11      Kenn  None  110.0    25632.0
12       Aly  None   90.0    25582.0
13      John  41.0   85.0  1528000.0

In [36]:
filled_df.isnull().sum()

Name      0
Age       0
Weight    0
Salary    0
dtype: int64

In [37]:
# Slicing and imputing columns at the same time
specific_cols = df[['Weight', 'Age']].fillna('Pending')

specific_cols

     Weight      Age
0      75.0     36.0
1      74.0     38.0
2      70.0     31.0
3      80.0     34.0
4     100.0     40.0
5   Pending     40.0
6      72.0     33.0
7      85.0     42.0
8      85.0     42.0
9      85.0     42.0
10    100.0  Pending
11    110.0  Pending
12     90.0  Pending
13     85.0     41.0

In [38]:
df2 = df.fillna(value={'Weight': 'Pending', 'Age': 'Unknown', 'Salary': '0.0', 'Name': 'Verification Pending'})

df2

                    Name      Age   Weight     Salary
0                  James     36.0     75.0  5428000.0
1                Villers     38.0     74.0  3428000.0
2                  VKole     31.0     70.0  8428000.0
3                  Smith     34.0     80.0  4428000.0
4                  Gayle     40.0    100.0  4528000.0
5                   Adam     40.0  Pending  4528000.0
6                 Rooter     33.0     72.0  7028000.0
7               Peterson     42.0     85.0  2528000.0
8                  lynda     42.0     85.0        0.0
9   Verification Pending     42.0     85.0        0.0
10                 Jenny  Unknown    100.0    25632.0
11                  Kenn  Unknown    110.0    25632.0
12                   Aly  Unknown     90.0    25582.0
13                  John     41.0     85.0  1528000.0

In [39]:
 # we are using a dictionary because dictionary using columns names
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }
tech = pd.DataFrame(technologies)

In [40]:
rows, cols = tech.shape
print(f'Rows: {rows}')
print(f'Columns: {columns}')

Rows: 7
Columns: 4

In [41]:
# summarize the null and count from tech 

tech.isnull().sum()

Courses     2
Fee         2
Duration    2
Discount    3
dtype: int64

In [42]:
tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [43]:
# Replace missing values
tech2 = tech.replace({np.nan: ' '})  # replacing Nan values into empty values
tech2

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [44]:
# Replace missing values
tech3 = tech.replace({'Courses':np.nan, 'Fee':np.nan}, 'PENDING')
tech3

   Courses      Fee Duration  Discount
0    Spark  20000.0      NaN    1000.0
1  PENDING  25000.0   40days       NaN
2   Hadoop  PENDING   35days    1500.0
3   Python  22000.0      NaN       NaN
4   pandas  24000.0   60days    2500.0
5  PENDING  PENDING   50days    2100.0
6     Java  22000.0   55days       NaN

In [45]:
tech.fillna(' ')
tech
# fillna() - fills the missing values with the empty value

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [46]:
# importing data from employee.csv
emp_df = pd.read_csv('data/employee.csv')

emp_df

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [47]:
# summarize the data values and count the misssing values present in the data
emp_df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [48]:
# we are going to fill the missing values with the unknown
emp_df = emp_df.fillna(value={'Name':
            'Unknown', 'Age': 'Unknown', 'Salary': 0.0,
            'Weight': 'Pending'})

emp_df

        Name      Age   Weight     Salary
0      James     36.0     75.0  5428000.0
1    Villers     38.0     74.0  3428000.0
2      VKole     31.0     70.0  8428000.0
3      Smith     34.0     80.0  4428000.0
4      Gayle     40.0    100.0  4528000.0
5       Adam     40.0  Pending  4528000.0
6     Rooter     33.0     72.0  7028000.0
7   Peterson     42.0     85.0  2528000.0
8      lynda     42.0     85.0        0.0
9    Unknown     42.0     85.0        0.0
10     Jenny  Unknown    100.0    25632.0
11      Kenn  Unknown    110.0    25632.0
12       Aly  Unknown     90.0    25582.0
13      John     41.0     85.0  1528000.0
14       Ali     26.0     69.0        0.0

#### Pandas DATE and TIME
- `pd.to_datetime` - convert different data types into datetime object
- `pd.date_range` - Used to generate a range of data and Time.
- `pd.timestamp` - generate the time expressed as number of seconds since 01/01/1970

In [49]:
# Generate a range of data from start to end , default frequency
date_range = pd.date_range(start='03/01/2026', end='05/05/2026')

print(date_range)

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05', '2026-03-06', '2026-03-07', '2026-03-08',
               '2026-03-09', '2026-03-10', '2026-03-11', '2026-03-12',
               '2026-03-13', '2026-03-14', '2026-03-15', '2026-03-16',
               '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20',
               '2026-03-21', '2026-03-22', '2026-03-23', '2026-03-24',
               '2026-03-25', '2026-03-26', '2026-03-27', '2026-03-28',
               '2026-03-29', '2026-03-30', '2026-03-31', '2026-04-01',
               '2026-04-02', '2026-04-03', '2026-04-04', '2026-04-05',
               '2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09',
               '2026-04-10', '2026-04-11', '2026-04-12', '2026-04-13',
               '2026-04-14', '2026-04-15', '2026-04-16', '2026-04-17',
               '2026-04-18', '2026-04-19', '2026-04-20', '2026-04-21',
               '2026-04-22', '2026-04-23', '2026-04-24', '2026-04-25',
               '2026-04-26', '2026-04-27', '2026-04-28', '2026-04-29',
               '2026-04-30', '2026-05-01', '2026-05-02', '2026-05-03',
               '2026-05-04', '2026-05-05'],
              dtype='datetime64[us]', freq='D')

In [50]:
# Generate a range of data from start to end , default frequency
# periods is number of dates yu want between start and end (inclusive)
date_range = pd.date_range(start='03/01/2026', end='05/05/2026',periods=4)

print(date_range)

DatetimeIndex(['2026-03-01 00:00:00', '2026-03-22 16:00:00',
               '2026-04-13 08:00:00', '2026-05-05 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [51]:
# Creating a DataFrame by passing a NumPy array with a datetime index using date_range() and frequency
date_range = pd.date_range(start='01/01/2020',end='05/05/2026',freq='QE')
date_range

DatetimeIndex(['2020-03-31', '2020-06-30', '2020-09-30', '2020-12-31',
               '2021-03-31', '2021-06-30', '2021-09-30', '2021-12-31',
               '2022-03-31', '2022-06-30', '2022-09-30', '2022-12-31',
               '2023-03-31', '2023-06-30', '2023-09-30', '2023-12-31',
               '2024-03-31', '2024-06-30', '2024-09-30', '2024-12-31',
               '2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31'],
              dtype='datetime64[us]', freq='QE-DEC')

In [52]:
date_range = pd.date_range(start='01/01/2024',periods=6, tz='Asia/Tokyo')
date_range

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-01-02 00:00:00+09:00',
               '2024-01-03 00:00:00+09:00', '2024-01-04 00:00:00+09:00',
               '2024-01-05 00:00:00+09:00', '2024-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [53]:
start_date = '01/01/2023'
num_days=30

date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

np.random.seed(42) # seed means we are all using the SAME random algorithm
# mean - 100
# std - 5
# 30 numbers
stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

stock_df = pd.DataFrame({'Date': date_range, 'StockPrice':stock_prices})

stock_df

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [54]:
start_date = '01/01/2023'
num_days=30

date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

np.random.seed(42) # seed means we are all using the SAME random algorithm
# mean - 100
# std - 5
# 30 numbers
stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

stock_df = pd.DataFrame({'Date': date_range, 'StockPrice':stock_prices})

stock_df

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [55]:
import datetime

timestamp = pd.Timestamp('2026-05-05 13:35:00' , tz='America/New_York')
print (timestamp)
print(type(timestamp))

dt_timestamp = datetime.datetime(2026, 5, 5 ,13 ,35)
print(dt_timestamp)
print(type(dt_timestamp))

converted_time = timestamp.tz_convert('Asia/Tokyo')

print(converted_time)

2026-05-05 13:35:00-04:00
<class 'pandas.Timestamp'>
2026-05-05 13:35:00
<class 'datetime.datetime'>
2026-05-06 02:35:00+09:00

In [56]:
timestamp.year

2026

In [57]:
timestamp.dayofweek

1

In [58]:
# converting 
dates = ['2026-05-05', '2024-01-13' , '2025-10-10']
print(dates)
print(type(dates))

#dates string must all be the same format
date_obj = pd.to_datetime(dates)
print(date_obj)
print(type(date_obj))

['2026-05-05', '2024-01-13', '2025-10-10']
<class 'list'>
DatetimeIndex(['2026-05-05', '2024-01-13', '2025-10-10'], dtype='datetime64[us]', freq=None)
<class 'pandas.DatetimeIndex'>

In [59]:
input_list = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

print(input_list)

output = pd.to_datetime(input_list,format='mixed')
print(output)

['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
DatetimeIndex(['2023-01-01 00:00:00', '2023-01-02 00:00:00',
               '2020-03-10 14:30:45', '2023-10-13 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [60]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})
df.info # to know datatypes

<bound method DataFrame.info of    patientID     name          date_of_birth
0        101    alice             2023-01-01
1         23      bob             2023-01-02
2         48  charlie       3/10/2020 143045
3         49     Eric  13th of October, 2023>

In [61]:
df['date_of_birth'].dtype

In [62]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')
df.head()

   patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00

In [63]:
df['date_of_birth'].dtype

dtype('<M8[us]')

In [64]:
df.info

<bound method DataFrame.info of    patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00>

In [65]:
df['date_of_birth'] = str(df['date_of_birth'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [66]:
df['date_of_birth'] = df['date_of_birth'].astype('str')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [67]:
# convert date into specific format
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'] , format='mixed' , errors='coerce')

print('code still running after error')
df

code still running after error

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [68]:
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
# Using parse dates to change type from string info date
tesla_df = pd.read_csv(url, parse_dates=['Date'])

# tesla_df.to_csv('data/tesla_stocks.csv')
tesla_df.head()
#tesla_df.info

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [69]:
# Add a new columns to dataframe based off of dates
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['day_name'] = tesla_df['Date'].dt.day_name()

tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Year,Day,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,2010,29,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,2010,30,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,2010,1,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2010,2,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,2010,6,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,2010,7,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,7,2010,8,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,7,2010,9,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,7,2010,12,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,7,2010,13,Tuesday

In [70]:
# grab max or min date from a dataset
most_recent_date = tesla_df['Date'].max()   # newest date
least_recent_date = tesla_df['Date'].min()   # oldest date

print(f'Most Recent Date: {most_recent_date}')
print(f'Least Recent Date: {least_recent_date}')

Most Recent Date: 2017-08-08 00:00:00
Least Recent Date: 2010-06-29 00:00:00

In [71]:
# Group by month and year and sum of the volume
# Groups your data by Year and Month combinations-
monthly_sales = tesla_df.groupby(['Year', 'Month'])['Volume'].sum().reset_index()

monthly_sales.head(15)

    Year  Month    Volume
0   2010      6  35953400
1   2010      7  64575800
2   2010      8  15038200
3   2010      9  18045900
4   2010     10   6547800
5   2010     11  28315100
6   2010     12  36892900
7   2011      1  28420100
8   2011      2  29303500
9   2011      3  32563300
10  2011      4  29894900
11  2011      5  30348800
12  2011      6  39727300
13  2011      7  21102100
14  2011      8  27215700

In [72]:
tesla_df

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Year,Day,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,2010,29,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,2010,30,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,2010,1,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2010,2,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,2010,6,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500,8,2017,2,Wednesday
1787,2017-08-03,345.329987,350.000000,343.149994,347.089996,347.089996,13535000,8,2017,3,Thursday
1788,2017-08-04,347.000000,357.269989,343.299988,356.910004,356.910004,9198400,8,2017,4,Friday
1789,2017-08-07,357.350006,359.480011,352.750000,355.170013,355.170013,6276900,8,2017,7,Monday
1790,2017-08-08,357.529999,368.579987,357.399994,365.220001,365.220001,7449837,8,2017,8,Tuesday

Filter using loc[] or query () -

In [73]:
# filtered_df_date = tesla_df.loc[tesla_df['Date'] >= '2010-08-01']
filtered_df_date = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01') & (tesla_df['Date'] <= '2010-12-31')]

# created a df of a range of dates using conditionals
# conditional filtering using dates
filtered_df_date

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Year,Day,day_name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,8,2010,2,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,8,2010,3,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,8,2010,4,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,8,2010,5,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,8,2010,6,Friday
...,...,...,...,...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900,12,2010,27,Monday
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300,12,2010,28,Tuesday
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200,12,2010,29,Wednesday
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100,12,2010,30,Thursday
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900,12,2010,31,Friday